adjective = input("Enter an adjective:")
noun = input("Enter a noun:")
nounp = input("Enter a plural noun:")
place = input("Enter a place:")
body = input("Enter a part of the body:") 
print("")
print("There are many", adjective,  "ways to choose a", noun, "to read.")
print("You could ask recommendations from your friends and", nounp + ".")
print("If they are no help, head to your local library or", place, "and browse the shelves")
print("until something catches your", body + ".")
